name: Laravel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Save Vendor Directory
        uses: actions/cache/save@v4
        with:
          enableCrossOsArchive: true
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ github.sha }}

  tests:
    needs: build

    runs-on: ubuntu-latest

    name: PHPUnit (PHP:8.3, Laravel:10)

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_USER: atte_user
          MYSQL_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Restore Vendor Diretory
        uses: actions/cache/restore@v4
        with:
          enableCrossOsArchive: true
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ github.sha }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Generate Key
        run: php artisan key:generate

      - name: Migration
        run: php artisan migrate

      - name: Execute tests
        run: php artisan test

  stub-tests:
    needs: build

    runs-on: ubuntu-latest

    name: Dusk (PHP:8.3, Laravel:10)

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_USER: atte_user
          MYSQL_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Restore Vendor Diretory
        uses: actions/cache/restore@v4
        with:
          enableCrossOsArchive: true
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ github.sha }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Generate Key
        run: php artisan key:generate

      - name: Migration
        run: php artisan migrate

      - name: Update Chrome Driver
        run: php artisan dusk:chrome-driver --detect

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php artisan serve --no-reload &

      - name: Run Dusk Tests
        run: php artisan dusk --without-tty --ansi
